pipeline {
  agent any

  environment {
    IMAGE = "yourdockerhubusername/devops-cicd-app:latest"
  }

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/yourusername/devops-cicd-project.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          dockerImage = docker.build("${IMAGE}", "./docker")
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
          dockerImage.push()
        }
      }
    }

    stage('Apply K8s Deployment') {
      steps {
        sh 'kubectl apply -f k8s/deployment.yaml'
        sh 'kubectl apply -f k8s/service.yaml'
      }
    }
  }
}
